### ISSUE TITLE
'Installation date' on deb shows as unknown 

### ISSUE THREAD

**Issue by anasereijo** [ubuntu/app-center#1200]
In the additional information section, the Installation date shows a 'Unknown' label for both uninstalled and installed DEB packaged.

It should display 'Not installed', or display the installation date when installed

<img width="1680" alt="Screenshot 2023-03-30 at 15 03 07" src="https://user-images.githubusercontent.com/36884067/228862072-6a5337e4-1bb2-45d8-9007-125f92546741.png">
<img width="1441" alt="Screenshot 2023-03-30 at 15 10 44" src="https://user-images.githubusercontent.com/36884067/228863755-511170aa-7244-40c2-8e76-68f4e9211fe9.png">

**Comment by dejvizelo** [comment]
For this issue there are two limitations:

- Unlike Snapd, PackageKit, which handles deb packages, does not provide the installation date of packages. However there is a workaround for this. As noted in [this bug thread](https://bugs.launchpad.net/appcenter/+bug/1512912) and [this issue thread](https://github.com/elementary/appcenter/issues/36) in ElementaryOS's AppCenter, PackageKit transactions can be filtered by package id and transaction role (the roles relevant here are "install-packages" and "update-packages"), and then the timespec property can be read from the [Transaction signal](https://www.freedesktop.org/software/PackageKit/gtk-doc/Transaction.html#Transaction::Transaction), which represent the timestamp when the Transaction was executed.
- This is where the second limitation comes in. Currently the [packagekit dart package](https://pub.dev/packages/packagekit) does not handle the Transaction signal (as seen [here](https://github.com/canonical/packagekit.dart/blob/faf2030382ea9f4518c6d6d45abe4760e81e1c91/lib/src/packagekit_client.dart#L910-L1054)).

I would like to open a PR in [packagekit](https://github.com/canonical/packagekit.dart) to handle the Transaction signal and then also address the issue here. Would really appreciate any thoughts you might have on this.
