### ISSUE TITLE
Way to show all categories and browse each categories

### ISSUE THREAD

**Issue by hsbasu** [ubuntu/app-center#1276]
Currently, the app shows only a few categories compared to what have been featured on [snap website](https://snapcraft.io/store). It would be nice to be able to see all categories.

Also, no option is there to browse all apps in a specific category. For example, similar to the website a **See more** button would be nice.

**Comment by d-loose** [comment]
All snap categories are shown on the explore page now.

**Comment by hsbasu** [comment]
@d-loose I am using this flutter based app-store from preview/edge channel with version *0.30-alpha*. But I am still unable to browse *all* individual categories. So I think this issue should be open.

**Comment by d-loose** [comment]
That is related to the now archived community store, which can still be accessed [here](https://github.com/ubuntu-flutter-community/software) as well as in the archive/* branches in this repo.

The new app-center (dev and main branch) is published in the `latest/stable/ubuntu-23.10` channel.

**Comment by d-loose** [comment]
Sorry, it's mildly confusing since there have been multiple name changes over the past few weeks :D

The new "App Center" is being developed in this repo here and published in the `latest/stable/ubuntu-23.10` channel of the [`snap-store`](https://snapcraft.io/snap-store) snap. So you can install it by running `snap install --channel=latest/stable/ubuntu-23.10 snap-store` (or rather `snap refresh ..` if `snap-store` is already installed).
