### ISSUE TITLE
Unable to update app-center without killing it 

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1391]
For app-center to update it needs to be killed on terminal manually, even if it is closed

**Comment by d-loose** [comment]
Are you referring to an update from the gnome-software based snap-store in latest/stable to this one here in latest/stable/ubuntu-23.10? This is a know issue due to the fact that gnome-software keeps running in the background and cannot be addressed here.

If you're experiencing this issue between different versions of the new app-center, I'd be happy if you could share more information. The process should terminate when you close the window and thus not block any updates.

**Comment by alculete** [comment]
I'm talking about this new version. 
I received an update yesterday, I saw it on installed apps, so I clicked it to update. As the app was running it didn't update and no notification was shown regarding this update being blocked for the running app. I closed the app and ran snap refresh on the terminal, received information that I couldn't update because the process was running (showed the process number) and I had to kill the process to proceed.

**Comment by d-loose** [comment]
Thanks for the clarification :slightly_smiling_face: 

First of all - the app center cannot update itself, because it simply tells snapd to do the update, which it can't do because the app center is running. We should try to come up with a solution for this eventually, though.

I'm well aware that you don't see any errors in that case (yet) - it's our next priority to address this (#1366).

I'll also investigate why the process didn't terminate in this case - this might be related to the lack of proper error handling at the moment.

**Comment by alculete** [comment]
Yes also seems like the pre-download is not working

**Comment by d-loose** [comment]
Related issue on launchpad: https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/2036765

**Comment by anasereijo** [comment]
This is now fixed.
