### ISSUE TITLE
The app name is App Center but shows snap-store in overview

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/app-center#1425]
![image](https://github.com/ubuntu/app-center/assets/72045785/29f39b32-1efd-4b19-92d3-cb6b8bdb41e1)

Currently I am on Ubuntu 23.04. Is this name intentional?

**Comment by FussuChalice** [comment]
Certainly! That's how it should be. Because we are making an application that can replace the old one in its architecture (the one used in these versions of Ubuntu). We gave the name "app-center" so as not to create confusion for developers.

**Comment by d-loose** [comment]
> Currently I am on Ubuntu 23.04. Is this name intentional?

Thanks for the bug report - while the name of the snap and the binary are still "snap-store", this isn't intentional and should read "App Center" as well.

**Comment by opxyc** [comment]
It's the same in 22.10 as well.

**Comment by sergio-costas** [comment]
I suspect that the reason is that the Gtk window underneath doesn't have set the window title. Check this screenshot:

![Captura desde 2023-12-13 17-59-00](https://github.com/ubuntu/app-center/assets/105285003/93c192e4-0f5a-40ff-8e71-a516b6343000)

You can see that the "terminus" window has an odd title, an UUID. That's because it is a trick that I used to integrate it with Gnome Shell, setting a specific UUID as the window title.

**Comment by sergio-costas** [comment]
So, by default, if no title is used, the binary name is used, I presume.

**Comment by sergio-costas** [comment]
Maybe the key is here?

![imagen](https://github.com/ubuntu/app-center/assets/105285003/f9dd5584-d662-4ede-a24f-ab680330260f)

**Comment by sergio-costas** [comment]
Ok, no... the trick isn't there.

**Comment by sergio-costas** [comment]
I found it.
