### ISSUE TITLE
New icon looks out of place comparing to other icons and seems to not follow yaru guide lines

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1625]
Before opening GitHub and seeing the bigger image in the PR  it was hard to understand the icon after the last upgrade.
At first glance looks like the paper bag handle is on the other side and the bag is open. After seeing the bigger icon seems the image is strached.

**Comment by Rexogamer** [comment]
the shorter icon, used until the latest commit, fits in far better and doesn't look quite as... off? the new one feels too tall. please reconsider.

**Comment by Feichtmeier** [comment]
Hello @anasereijo, great to have you back👋 

instead of creating a new issue we can take this one instead

The differences between the new icon and the yaru icon guidelines include the following:

- the border is too thick
- the outlines are too strong
- the shadows of the upper half are too strong

![grafik](https://github.com/ubuntu/app-center/assets/15329494/b7447403-c8d1-4317-b7cb-cd68fb450813)

The differences become visible in the different sizes that icons can have in the ubuntu dock, making it look more pronounced and glossy and generally "more 3D"/skeuomorph

![Bildschirmfoto 2024-04-04 um 20 45 45](https://github.com/ubuntu/app-center/assets/15329494/231b62ff-141d-4192-a9b2-151e62dd16a1)

For a good overview of all full color icons you can either click through the yaru full color directory
or use the web app and click on "YaruIcons, full color"
https://ubuntu.github.io/yaru.dart/

Here is a nice guide on how to follow the yaru icon guidelines written by @ubuntujaggers:
https://github.com/ubuntu/yaru/wiki/%234-Help-for-creating-yaru-icons

Here are base plate SVGs one can use inside Inkscape to start from scratch

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/Horizontal%20Oblong%20App%20Icon%20Template.svg

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/Round%20App%20Icon%20Template.svg

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/Square%20App%20Icon%20Template.svg

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/Vertical%20Oblong%20App%20Icon%20Template.svg

As mentioned on discord @ubuntujaggers already created a refined version of your new app icon:
![grafik](https://github.com/ubuntu/app-center/assets/15329494/3a90dad2-ca22-429a-aa1f-3d70188ddb0e)

![yarufied_app_centre_icon](https://github.com/ubuntu/app-center/assets/15329494/a379012f-a4ce-49e5-941f-4d9f1db2638b)

Thanks for connecting

**Comment by anasereijo** [comment]
Thanks for providing this, @Feichtmeier. I shared with the brand team. They will have a look asap!

**Comment by anasereijo** [comment]
@Feichtmeier the brand team is happy to proceed with the version @ubuntujaggers worked on! 
@ubuntujaggers: Would you also like to improve/work on the other new icons? We can then get the team's approval again.

Thank you so much.

**Comment by ubuntujaggers** [comment]
Hi guys, would love to help 🙂 I am going to be away till early May - will check in with you when I'm back! Thanks all 👍

**Comment by Feichtmeier** [comment]
> @Feichtmeier the brand team is happy to proceed with the version @ubuntujaggers worked on! @ubuntujaggers: Would you also like to improve/work on the other new icons? We can then get the team's approval again.
> 
> Thank you so much.

Thanks everyone for the nice colab!

This also about the installer icon, right?
For starters, should I create an issue on the installer repo similar to this one here and tag everyone? So stuart can refine the icon when he finds time?

**Comment by anasereijo** [comment]
> > @Feichtmeier the brand team is happy to proceed with the version @ubuntujaggers worked on! @ubuntujaggers: Would you also like to improve/work on the other new icons? We can then get the team's approval again.
> > Thank you so much.
> 
> Thanks everyone for the nice colab!
> 
> This also about the installer icon, right? For starters, should I create an issue on the installer repo similar to this one here and tag everyone? So stuart can refine the icon when he finds time?

yes, please! as soon as we have the new icon for the installer, we can get brand's approval. thank you

**Comment by ubuntujaggers** [comment]
Apologies all that this is much later than I originally said - if you still have any other new icons that you would like me to look at in terms of "Yaru-ness" 🙂 then I would be happy to look at them 👍
