### ISSUE TITLE
Elephant in the room: adding support for flatpak

### ISSUE THREAD

**Issue by All3xJ** [ubuntu/app-center#1670]
I'm quoting an answer of another github issue:
> I understand the desire to have a “one-stop shop” to find software, however the goal of this project is to provide the best out-of-the-box experience on Ubuntu. We believe that snaps provide the best combination of security and usability for Ubuntu users and our priority is to deliver a tailored, intuitive and accessible way for users of all experience levels to find the apps that they need.
> 
> For users who are looking for a more generalized store, we recommend gnome-software, which will continue to be available in the Ubuntu repository and is designed to be compatible with a wide variety of packaging formats, including Flatpak.

I understand this, but if you say "the goal of this project is to provide the best out-of-the-box experience on Ubuntu", well this is not the case. Because if a user (like me) uses Ubuntu and wants to use both snap and flatpak, is forced to install another app store if doesn't want to operate via commandline.
This is NOT the "best out-of-the-box experience on Ubuntu".

Also, if Ubuntu (and I understand this) wants to "push" a user to use snap, you can still do this. I mean, you can just leave everything as it is, so by default only snap is enabled and app-center only shows snap and debs.
Then, IF and only IF the user wants to install also flatpak, then app-center "detects" this and starts showing also flatpak results (as THIRD choice, in order to push for snap and repo as first choices)

Why not? This app-center store is VERY good. I mean, it's much better than gnome-software-center, so why you prevent a user to have everything in a single store?

**Comment by ricperry** [comment]
Ubuntu store only supporting snaps is not the best out-of-box experience though. MANY popular apps only have partial support (if any) for snap, and their websites explicitly recommend the flatpaks or appimages.

**Comment by carafelix** [comment]
Please add flatpak support to it.  There is a clear UX advantage of having the ability to install software that it's not distributed as a snap... (I for example use Gmetronome, that does not have a snap).

A little but super annoying thing is, I hate that when having the gnome-software app installed too, when clicking on "show details" in any app in the activity menu (Super + A), it does not recognize the snap package, nor the other way around
. 
And there is really no reason for avoiding flatpak listing at all. They exist for a reason, and no support for them is really hurting the UX. The app center already have's a channel drop down menu, so why not add a flathub listings there.
 
We all know Canonical is pushing for snaps, I myself like them because they are easy to package, but this blind stab to flatpaks is outrageous. Already requested in #30 #1336 #126

**Comment by d-loose** [comment]
I'd suggest taking this discussion to https://discourse.ubuntu.com (e.g. [here](https://discourse.ubuntu.com/t/flatpak-is-a-missed-opportunity/34189)), as this feature request reaches far beyond the scope of the app center and affects the entire desktop.

**Comment by rgreening** [comment]
The "excuse" of it being a best out of box experience is not actually the reason. It is plainly to force snap adoption. Plain and simple. It is pushing everyone to that direction. 

Prove me wrong and allow Flatpak. Otherwise, its clear, the direction is to push only snap. In fact, if deb's could be removed entirely, the store would only support snaps. That much is clear. Even some deb's are no longer deb's but wrappers for snaps. So the whole best out of box experience actually means Canonical believes only in snaps. 

Again, prove me wrong.
