### ISSUE TITLE
Explore text in light mode is black on black

### ISSUE THREAD

**Issue by richelbilderbeek** [ubuntu/app-center#1735]
Hi,

Thanks for writing and maintaining the App Center!

At Noble Nimbat, when exploring, I see my prompt display black letters (ok!) on a dark background (not ok!):

![Screenshot from 2024-07-10 09-28-33](https://github.com/ubuntu/app-center/assets/2098230/1e39ed1c-6bb2-461f-a9ba-7979c05eb8a0)

I use light (i.e. non-dark) mode whenever I can and I use these Accessibility settings:

![Screenshot from 2024-07-10 09-35-36](https://github.com/ubuntu/app-center/assets/2098230/6dcb47a2-2aa7-49d6-8ae9-8ec77a40c7f2)

I hope this gives all info you need. If not, I'd be happy to provide more!

Thanks and cheers, Richel Bilderbeek

**Comment by Feichtmeier** [comment]
Hi, this is fixed in #1731
It will take some time to land in in the channel you are using I suppose, but you can test it from the latest/edge channel (but only if you are really sure you want to test development versions :))

@d-loose since this is kind of a heavy issue for people using HC modes you should eventually push this to the stable channels

**Comment by richelbilderbeek** [comment]
Thanks @Feichtmeier for the awesome job! Dass is ja der Hammer!
