### ISSUE TITLE
app-center downgraded to version 41.* [Channel=latest/edge]

### ISSUE THREAD

**Issue by alculete** [ubuntu/app-center#1816]
app-center downgraded to version 41.* and name changed to **Ubuntu Software**

![image](https://github.com/user-attachments/assets/20dcdaf2-1159-47df-8ed4-40d163cf3937)

**Comment by d-loose** [comment]
Thanks for catching this! A bug fix for gnome-software (which is available in `latest/stable` and is still needed for older LTSs) unintentionally made its way into `latest/edge` instead of `latest/candidate`. Should be fixed now :).
Maintaining two different code bases in the same snap track is quite confusing and error prone - we're currently in the process of migrating to a cleaner setup, see [here](https://discourse.ubuntu.com/t/ubuntu-desktop-s-24-10-dev-cycle-part-4-august-update/47217#seeded-snap-tracks-for-desktop-apps).

**Comment by alculete** [comment]
I normally use edge channel for bug reporting and new features. Will still this available after these changes?

**Comment by d-loose** [comment]
Yes, anything merged into `main` will be available in the `2/edge` channel (currently `latest/edge` and `2/edge` always contain the latest development version of the app center).
