### ISSUE TITLE
[Feature Request] Incorporate "Software & Updates" and "Software Updater"

### ISSUE THREAD

**Issue by ricjcs** [ubuntu/app-center#423]
"Ubuntu Software", "Software & Updates" and "Software Updater", are 3 Ubuntu graphical applications for managing software and updates.

It would be interesting that the new Ubuntu Software integrates the "Software & Updates" and "Software Updater", so it would be unnecessary to have 3 applications to manage the software, in a single application everything would be managed.

**Comment by Feichtmeier** [comment]
Yeah that's also my goal.
The source last can be currently set to up in the update page but this should move to the settings tab eventually.
Will discuss this with the others, thanks for the issue

**Comment by Feichtmeier** [comment]
@robert-ancell since you made half of the apps, implementations and libs on this topic:

- we got system updates in
- we got repository settings in
- we miss system upgrades (apt.dart?)
- what would be the best option to get the drivers panel in?

**Comment by robert-ancell** [comment]
@Feichtmeier I'm not sure what you're asking here, but this sounds like a design question.

**Comment by Feichtmeier** [comment]
Basically the same as in the apt discussion but this time in concrete for this specific issue

**Comment by Muqtxdir** [comment]
excluding drivers tab and here's the unstable prototype demo:

[Screencast from 2023-03-21 23-04-32.webm](https://user-images.githubusercontent.com/54065734/226695287-ccb882a2-e1a6-411e-b7b2-a9d744c8a7b1.webm)

**Comment by Feichtmeier** [comment]
Some information extracted from the various discussions in the video call:

- The ideal solution would be to only show those Debian package updates inside the manage Debian page that are NOT part of the Ubuntu system/desktop. For example Google Chrome, 0ad-data ppas, because users wouldn't call their system apps and vice versa 
- all system/Ubuntu desktop only packages should be shown in a second app "system updater" if it's the current python app or a new flutter app doesn't matter from a design perspective

To continue on this:
the *settings* of of the system updates could (currently called software and updates) could be the same UI as the updater itself, IMO. Or wdyt @local-optimum @anasereijo or anyone else with an opinion
