### ISSUE TITLE
Dependecies popup has scrollbar in headerbar

### ISSUE THREAD

**Issue by madsrh** [ubuntu/app-center#842]
![image](https://user-images.githubusercontent.com/3986894/213861868-fd084679-c682-46f7-b707-727eb0f31909.png)

**Comment by Feichtmeier** [comment]
its not really a bug, just the way this dialog is built - but still an issue 👍

**Comment by madsrh** [comment]
> its not really a bug, just the way this dialog is built - but still an issue

Right, it should not move into the headerbar.

😨 Don't assign this to me 🙈 💩 I've already tried to fix this, moving the `scrollable: true` around, but no luck. I'll better leave it to the professionals. 

It should work like here:
![image](https://user-images.githubusercontent.com/3986894/213862641-ba70d0ea-31e4-4376-94fe-6cfffe6a9479.png)

**Comment by Feichtmeier** [comment]
Exchange AlertDialog with SimpleDialog and move the children of this column as the children of the simple dialog

**Comment by Feichtmeier** [comment]
> Exchange AlertDialog with SimpleDialog and move the children of this column as the children of the simple dialog

That was a really bad tip and just plain wrong since we also got actions 😄 

- remove `scrollable: true`, since the default should be false
- replace `Column` with `ListView`
- click with your mouse on "ListView" and then press "CRTL" + "." 
- select "wrap with sized box" and give it height and width
- set the property `shrinkWrap` to `true` in the `ListView`

https://github.com/ubuntu-flutter-community/software/blob/433bab77975d6453ee480f8d6605942ca567b71f/lib/app/common/packagekit/package_page.dart#L255-L334

**Comment by madsrh** [comment]
Thanks 😊 I will give this a try later

**Comment by madsrh** [comment]
Okay, something went wrong 😄 
I think you should just fix this 🙈 You'll have to revisit the popup anyway for dependencies list makeover. I'm very happy just replacing strings and typos 😅 

![image](https://user-images.githubusercontent.com/3986894/213917361-5f49a660-f9b5-40f3-8a08-336af31bd12d.png)
